### ISSUE TITLE
How to transition old pads using ep_headings to ep_headings2?

### ISSUE THREAD

**Issue by mestaritonttu** [ether/ep_headings2#4]
I have ep_headings and ep_headings2 installed.
If I uninstall ep_headings and go to a pad that has headings created with it, I get an error message referring to some template not found in ep_headings folder.
How can I solve this?

**Comment by JohnMcLear** [comment]
look at the source code and figure it out?

**Comment by mestaritonttu** [comment]
I could not reproduce this in a fresh install. Installed ep_headings, created a pad and set text to heading. When I uninstalled it, the heading was shown *like this.

I tried to solve it in the problematic install by resetting the heading style to normal in the affected pad I was testing with, but no luck.

Here is the error message:

```
Error: ejs:67
   65|                 <% e.begin_block("editbarMenuLeft"); %>
   66|                 <%- toolbar.menu(settings.toolbar.left) %>
>> 67|                 <% e.end_block(); %>
   68|             </ul>
   69|             <ul class="menu_right" role="toolbar">
   70|                 <% e.begin_block("editbarMenuRight"); %>

Cannot find module 'ep_headings/templates/editbarButtons.ejs' from '/home/etherpad/etherpad-lite/node_modules/ep_etherpad-lite/templates'
   at Function.module.exports [as sync] (/home/etherpad/etherpad-lite/src/node_modules/resolve/lib/sync.js:33:11)
   at Object.exports.require (/home/etherpad/etherpad-lite/src/node/eejs/index.js:106:25)
   at Object.exports.eejsBlock_editbarMenuLeft [as hook_fn] (/home/etherpad/etherpad-lite/node_modules/ep_headings/index.js:4:38)
   at normalizedhook (/home/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
   at hookCallWrapper (/home/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
   at /home/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:76:14
   at Function._.map._.collect (/home/etherpad/etherpad-lite/src/node_modules/underscore/underscore.js:172:24)
   at Object.exports.callAll (/home/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:75:24)
   at Object.exports.end_block (/home/etherpad/etherpad-lite/src/node/eejs/index.js:82:9)
   at eval (eval at <anonymous> (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:455:12), <anonymous>:51:10) ``

**Comment by JohnMcLear** [comment]
I'm available as a gun for hire if you want me to fix this for you.  I'm not going to fix it for free though because it's not a problem with my code :)

**Comment by mestaritonttu** [comment]
I'm a volunteer gun in the LibreOffice project so I'll probably badger our infra team about it. I'll update and close, when the cause is found.
